### ISSUE TITLE
Build fails on Windows 10

### ISSUE THREAD

**Issue by crowne** [mtxr/vscode-sqltools#271]
**Describe the bug**
The build fails on Windows 10 with the following error:
webpack not installed, consider installing it using 
npm install --save-dev webpack

It is installed in root/node_modules/.bin
I also tried running the install command above in packages/extension, but got the same result.

**To Reproduce**
1. Clone repository
2. Open in VSCode
3. Click "Terminal/Run Build Task..."

**Expected behavior**
Build success

**Screenshots**
> Executing task in folder root: npm run watch <

> sqltools@0.19.5 prewatch E:\projects\vscode-sqltools
> yarn run clean

yarn run v1.16.0
warning sqltools@0.19.5: The engine "vscode" appears to be invalid.
$ rimraf -rf ../dist
Done in 0.36s.

> sqltools@0.19.5 watch E:\projects\vscode-sqltools
> yarn workspace @sqltools/extension watch

yarn workspace v1.16.0
yarn run v1.16.0
warning @sqltools/extension@0.19.5: The engine "vscode" appears to be invalid.
$ cross-env NODE_ENV=development webpack --watch --info-verbosity verbose

webpack not installed, consider installing it using 
npm install --save-dev webpack

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: C:\Program Files\nodejs\node.exe
Arguments: C:\Program Files (x86)\Yarn\lib\cli.js watch
Directory: E:\projects\vscode-sqltools\packages\extension
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqltools@0.19.5 watch: `yarn workspace @sqltools/extension watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqltools@0.19.5 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Neil\AppData\Roaming\npm-cache\_logs\2019-06-13T13_59_25_814Z-debug.log
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.

**Desktop (please complete the following information):**
 - SQLTools Version 0.19.5
 - VSCode Version: 1.35.1
 - Dialect Used: n/a
 - OS: Windows 10
 - node --version = v10.15.3
 - npm --version = 6.4.1
 - yarn --version = 1.16.0
 - .\node_modules\.bin\webpack --version = 4.33.0 

**Additional context**

**Comment by mtxr** [comment]
Hi, 

sorry for the late reply, I had to deal with some stuff here in the past week, I'll take a look at this within this week.

Thanks!

**Comment by mtxr** [comment]
Are you running using `npm run watch` or `yarn run watch`?

This project rely 100% on yarn. I looks like a bug with NPM since we are using workspaces.

Anyway I've changed the script command to use relative paths for webpack. Should work now with NPM too. But I discourage NPM usage for now.

**Comment by crowne** [comment]
My default way of building is:

- git clone
- open in vscode
- Terminal / Run Build Task (Ctrl + Shift + B)

This seems to launch `npm run watch`

I'm up to date with the master branch, and I tried building from command line both npm and yarn, but I was still getting errors.
After deleting the node_modules directory and rerunning `npm install` it seemed to fix the issue,
so now I can compile - Thanks!

**Comment by mtxr** [comment]
Awesome @crowne!
